using System;
using System.CodeDom.Compiler;

namespace Windows.Win32.Devices.Display;

[Flags]
[GeneratedCode("Microsoft.Windows.CsWin32", "0.3.275+02bc0c298e.RR")]
public enum SET_DISPLAY_CONFIG_FLAGS : uint
{
	SDC_USE_DATABASE_CURRENT = 0xFu,
	SDC_TOPOLOGY_INTERNAL = 1u,
	SDC_TOPOLOGY_CLONE = 2u,
	SDC_TOPOLOGY_EXTEND = 4u,
	SDC_TOPOLOGY_EXTERNAL = 8u,
	SDC_TOPOLOGY_SUPPLIED = 0x10u,
	SDC_USE_SUPPLIED_DISPLAY_CONFIG = 0x20u,
	SDC_VALIDATE = 0x40u,
	SDC_APPLY = 0x80u,
	SDC_NO_OPTIMIZATION = 0x100u,
	SDC_SAVE_TO_DATABASE = 0x200u,
	SDC_ALLOW_CHANGES = 0x400u,
	SDC_PATH_PERSIST_IF_REQUIRED = 0x800u,
	SDC_FORCE_MODE_ENUMERATION = 0x1000u,
	SDC_ALLOW_PATH_ORDER_CHANGES = 0x2000u,
	SDC_VIRTUAL_MODE_AWARE = 0x8000u,
	SDC_VIRTUAL_REFRESH_RATE_AWARE = 0x20000u
}
