<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>VitureCommonLibrary</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.0</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>11.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="System.Memory">
      <HintPath>..\..\..\..\..\..\..\..\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.36\System.Memory.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Win32.Registry">
      <HintPath>..\..\..\..\..\..\..\..\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.36\Microsoft.Win32.Registry.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>..\..\..\..\..\..\..\..\Program Files\VITURE\SpaceWalker\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="YamlDotNet">
      <HintPath>..\..\..\..\..\..\..\..\Program Files\VITURE\SpaceWalker\YamlDotNet.dll</HintPath>
    </Reference>
    <Reference Include="NLog">
      <HintPath>..\..\..\..\..\..\..\..\Program Files\VITURE\SpaceWalker\NLog.dll</HintPath>
    </Reference>
    <Reference Include="LibUsbDotNet.LibUsbDotNet">
      <HintPath>..\..\..\..\..\..\..\..\Program Files\VITURE\SpaceWalker\LibUsbDotNet.LibUsbDotNet.dll</HintPath>
    </Reference>
    <Reference Include="System.Management" />
  </ItemGroup>
</Project>