using System;

namespace VitureCommonLibrary;

[Flags]
public enum DisplayConfigTargetStatus : uint
{
	DISPLAYCONFIG_TARGET_DEFAULT = 0u,
	DISPLAYCONFIG_TARGET_IN_USE = 1u,
	DISPLAYCONFIG_TARGET_FORCIBLE = 2u,
	DISPLAYCONFIG_TARGET_FORCED_AVAILABILITY_BOOT = 4u,
	DISPLAYCONFIG_TARGET_FORCED_AVAILABILITY_PATH = 8u,
	DISPLAYCONFIG_TARGET_FORCED_AVAILABILITY_SYSTEM = 0x10u,
	DISPLAYCONFIG_TARGET_IS_HMD = 0x20u
}
