namespace VitureCommonLibrary;

public enum HidAckState : byte
{
	ERR_SUCCESS,
	ERR_FAILURE,
	ERR_INVALID_ARGUMENT,
	ERR_NOT_ENOUGH_MEMORY,
	ERR_UNSUPPORTED_CMD,
	ERR_CRC_MISMATCH,
	ERR_VER_MISMATCH,
	ERR_MSG_ID_MISMATCH,
	ERR_MSG_STX_MISMATCH,
	ERR_CODE_NOT_WRITTEN
}
